### ISSUE TITLE
db name hardcoded to "door-display"

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#13]
The documentation for db creation specifies to pick a db name.  The code in get_image.sh is hard-coded to use a db named "door-display".  Hyphenated db names can be problematic and should be avoided.  In fact, all special characters should be avoided in db and table names.  Please add a field in settings.cfg that will process the db name and use it in get_image.sh.

**Comment by AndersenJ** [comment]
This works as of cd8e66a.
