### ISSUE TITLE
Need to do a security audit of get_image.php

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#37]
Most of the wall-ink-server website is hidden behind .htaccess files.

The get_image.php script is publicly available to query.

The existing get_image.php script includes a basic sanity check.  It can handle unknown mac addresses.  How will it handle SQL injection?  How will it handle a buffer overrun?  The php script should truncate all inputs over a certain number of characters to prevent malicious code execution.

**Comment by AndersenJ** [comment]
Finished.
