### ISSUE TITLE
QR Code points to wrong place for google calendars

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#4]
URL for QR code for google calendars should be:

https://calendar.google.com/calendar/embed?src=<calendarID>%40group.calendar.google.com&ctz=America%2FDenver

America%2FDenver is the time zone of the device.  If the resulting QR code is too large, we should nix the QR code for the google calendars completely.

**Comment by AndersenJ** [comment]
It has been decided that these urls shall be placed in a config file

**Comment by AndersenJ** [comment]
Fixed as of aa269a7
