### ISSUE TITLE
New URL sanitization code has stopped google plugin from working

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#41]
Google plugin resources now throw error when manually checking get_png.php

REGEX doesn't match

**Comment by jdeananderson** [comment]
It also broke the simple text plugin, because the simple text plugin uses underscores in filenames of php files

https://myserver.com/get_png.php?mac_address=AAAAAAAAAAAA&layout=30&scheduling_system=4&resource_id=sample_text&voltage=7&width=640&height=384

**Comment by AndersenJ** [comment]
Looks like this is fixed now.
