### ISSUE TITLE
Replace word "Room" with "Booked Resource" and "Google Calendar

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#5]
On a device page where you select the layout, the drop down list for "room" should be "Booked Resource" for Booked and "Google Calendar" for google instead of "Room".  The word "room" doesn't quite work for either instance since booked resources may be equipment, cars, people, etc, and in google, you are choosing which calendar to use.

**Comment by AndersenJ** [comment]
Fixed as of ab4ab1f.
