### ISSUE TITLE
Optional automatic registration of unknown MAC addresses

### ISSUE THREAD

**Issue by jdeananderson** [caedm/wall-ink-server#63]
It would be nice to have an option to turn on adding MAC addresses of unknown devices to the device database.  This option would need to be off by default, and enabled manually.  This would allow bulk registration of batches of new devices, and then turn the option off for normal operation to ensure that hackers do not fill the device database with who-knows-what.  Considering the option of enabling this feature in either the config file, or from the website.  Using the config file would probably be easier, but not as convenient.

**Comment by AndersenJ** [comment]
This is fixed as of 61a7fe936251e50048e9f824d5c5ea8c157b9fed (v4.02b).
