### ISSUE TITLE
Issue building on mac

### ISSUE THREAD

**Issue by b3z** [caedm/wall-ink-server#72]
If I try to `make` the wall-ink-server I get the following issue:

```bash
lucamac:wall-ink-server luca$ make
MAKELEVEL=0
bash -c "source ./web/config/settings.cfg; \
		for var in \$(compgen -v); do export \$var; done; \
		/Applications/Xcode.app/Contents/Developer/usr/bin/make deploy"
MAKELEVEL=1
g++ image.o BitBuffer.o QrCode.o QrSegment.o processImage.o sha1.o layouts.o Adafruit_GFX.o -static -O1 -std=c++11 -DIMAGE_KEY=\"hunter2\" -DTIME_ZONE=-7 -o web/genimg
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [genimg] Error 1
make: *** [deploy] Error 2

```

I am running on MacOS 10.15
Any idea how to fix that. How to get the library?

**EDIT**

Found this one https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag

Seems to be a MacOS issue, did anyone ever built on MacOS?

**Comment by AndersenJ** [comment]
We don't support Mac OS, and as far as I know this project has never been built for Mac OS. I suggest trying this with a Linux virtual machine. I'll leave this open for a little longer just in case someone is actually able to help you though.

**Comment by b3z** [comment]
Alright. Thanks for your help, I can live with Linux so I am going to close here.
