### ISSUE TITLE
Nagios error messages

### ISSUE THREAD

**Issue by b3z** [caedm/wall-ink-server#74]
Another issue I have now is during Nagios testing:

```bash
$ ./check_wall_ink_server.sh -u "http://127.0.0.1/wall-ink/get_image.php"
-u: setting url to: http://127.0.0.1/wall-ink/get_image.php
CRITICAL - data is too small or NULL
```

I didn't find any description what the error message really means or what the issue is. 
Is there further information?
Any hints?

**Comment by emdarcher** [comment]
Yes, unless you specified the `mac_address` and `image_key` variables inside the script to be the same ones as in your server, you will need to have the `-i` and `-m` flags along with their parameters as shown in the [readme](https://github.com/caedm/wall-ink-server/tree/master/wall-ink-nagios-script#basic-usage). 

The error message:
```
CRITICAL - data is too small or NULL
```
means that the script is not getting a valid amount of data returned by the server, or no data at all. 
In this case it probably isn't getting any image data back from the server, but at the same time the server isn't giving any HTTP errors, or the error message would have been different.

You may want to try running it in verbose mode with the `-v` flag to get more information. If you need even more information you could run it in debug mode with the `-d` flag as well.

**Comment by b3z** [comment]
Alright even with -I and -m set I still get the `CRITICAL - data is too small or NULL` message. 

Verbose also tells me HTTP 200 OK so the problem seems to be my server which is not working properly.

**Comment by AndersenJ** [comment]
Okay. Could you run that command with the -v and -d flags, censor out anything sensitive (like your image key), and post the output? That can be useful for debugging the server too.

Also, are you able to access the device manager site? Does it show images when you select a device?

**Comment by b3z** [comment]
```bash

./check_wall_ink_server.sh -u "http://127.0.0.1/wall-ink/get_image.php" -m "xx:xx:xx:xx:xx:xx" -I "hunter" -v -d
-u: setting url to: http://127.0.0.1/wall-ink/get_image.php
-m: setting Mac Address to: xx:xx:xx:xx:xx:xx
-i: setting image key to: hunter7
-v: setting to verbose
-d: debug mode active
URL Query: http://127.0.0.1/wall-ink/get_image.php?mac_address=xx:xx:xx:xx:xx:xx&firmware=nagios&error=0&voltage=4.00&width=640&height=384
http_info =   HTTP/1.1 200 OK
http_code = 200
bytes = 0
CRITICAL - data is too small or NULL

```

I don't have any physical devices, only a virtual one. But I don't see any images when I select a device `error: image not found`

![image](https://user-images.githubusercontent.com/47346598/65539791-66ddf500-df0a-11e9-8000-9ffd622adc8c.png)

**Comment by AndersenJ** [comment]
Could you set debugModeActive to "true" in your settings.cfg, rebuild, and visit try to visit the web page for the image that the edit_device.php page is trying to display? You might get a useful error message that way.
