### ISSUE TITLE
Webserver not displaying PNG version of images

### ISSUE THREAD

**Issue by danhogwood** [caedm/wall-ink-server#75]
I have installed the wall-ink-server on Ubuntu Server 20.04 with all of the dependencies listed in the read me.

The server is communicating with the device however the image transmitted is always blank. I have confirmed the screen is working using the admin mode which displays the admin screen warning and QR code okay.

When following the troubleshooting advice to review the device page for the png image I have found one does not exist. There is no evidence in any of the logging as to why this may be.

**Comment by AndersenJ** [comment]
Does it work if you try using a different plugin, such as the static images plugin?

It's possible that this is an issue that's new to Ubuntu 20.04. Have you tried Ubuntu 18.04 to see if the issue exists there too?

**Comment by danhogwood** [comment]
Thanks for the very prompt response @AndersenJ - I traced the issue and found a solution. I needed to install imagemagick as the conversion element was failing. Everything is working perfectly now.
