### ISSUE TITLE
iCalPlugin image is not loading

### ISSUE THREAD

**Issue by elmiba** [caedm/wall-ink-server#76]
Hi,
I'm trying to get the iCalPlugin running but it won't display anything. 
I have put in my Outlook ICS file link and it seems not to load any data.
I have checked the link if a typo would be in there...

The example calendars are functioning just fine.

There is only a white square displayed when I try to get the pic manually... No error message as "usual".

thanks!

**Comment by jdeananderson** [comment]
You may want to start by verifying that your iCal file can be successfully processed by the iCalParser at https://github.com/caedm/icalparser.  The iCalParser reads your iCal file and grabs the scheduled events from it to be displayed by the Wall-ink server.   Its possible that your iCal file cannot be read by OzzyCzech's code for some reason.  Formatting issues, or something new or unexpected in your file, etc.

If that doesn't pan out, perhaps try the updated code from the original author at https://github.com/OzzyCzech/icalparser and see if that works.  Our Outlook files are still working, but yours may be different in some way.  Perhaps try a simpler iCal file first?

If the iCalParser is working fine, but the Wall-ink server continues to not display them, then that is a different issue and we will have to look into it.

Good luck,  --Dean

**Comment by elmiba** [comment]
Hi Dan,

Thanks for your quick response. I could not figure out what the problem was but it just fixed it self somehow. I think it has to do with Outlook rather than the Wall-Ink project.

Thanks a lot!
Regards
