### ISSUE TITLE
Got Permission denied Error

### ISSUE THREAD

**Issue by ghosoft** [caedm/wall-ink-server#77]
Deploy wall ink server on a raspberry pi
![image](https://user-images.githubusercontent.com/4844538/88877880-1e454580-d259-11ea-95ff-d5ef91477965.png)
![image](https://user-images.githubusercontent.com/4844538/88877884-23a29000-d259-11ea-9d7c-3935151211a7.png)

Test from browser like this:
http://192.168.20.175/wallInkServer/get_image.php?mac_address=AAAABBBBCCCC&firmware=9.9&error=0&voltage=3.12&width=640&height=384

and got  error:
Warning: file_put_contents(log/AAAABBBBCCCC.log): failed to open stream: Permission denied in /var/www/html/wallInkServer/get_image.php on line 86

Warning: fopen(image_data/AAAABBBBCCCC.info): failed to open stream: Permission denied in /var/www/html/wallInkServer/plugin_dependencies/general_scheduling/schedulingGetImage.php on line 25
Unable to open file

**Comment by jdeananderson** [comment]
Looks like you need to check the permissions on your web server.  It's not able to write the various files it needs to operate.  It's saying that it can't write to the log, and can't open the .info file.  Check your permissions.  We have not tested the server on a Raspberry Pi, but I believe it could be made to work.  Good luck.

**Comment by ghosoft** [comment]
yes,  i changed the permission
![image](https://user-images.githubusercontent.com/4844538/88892255-14323f80-d277-11ea-96b3-91337440219b.png)

now it 'almost' work, but can not see preview image, please tell me how to debug : )
![image](https://user-images.githubusercontent.com/4844538/88892344-2f9d4a80-d277-11ea-8004-0726e68dd772.png)

**Comment by ghosoft** [comment]
Could you please give a simple tutorial on how to setup a php/mysql server , 
I tried 3 times, but Never succeeded. 
Like the screenshot above, The page cannot display pictures.

**Comment by ghosoft** [comment]
Or make a script that setup environment on a newly install mechine?

**Comment by ghosoft** [comment]
this is my installation log:   
but finally failed, What did i do wrong?
\\
\\
\\
\\
\\



![image](https://user-images.githubusercontent.com/4844538/89699486-cd6cd580-d959-11ea-8d4c-716153736baf.png)

**Comment by ghosoft** [comment]
Something strange happened!😀
After i installed the ubuntu desktop
sudo apt install xubuntu-desktop
It works!

![image](https://user-images.githubusercontent.com/4844538/89701087-7d484000-d966-11ea-8603-95d348aa93d2.png)
